app/routes/games.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from datetime import datetime
from .. import db, login_manager
from ..models import User, Game, participants, pending_participants
from ..forms import RegistrationForm, LoginForm

bp = Blueprint('games', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@bp.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        dates = request.form['datetimes']
        start_time, end_time = dates.split(' - ')
        start_time = datetime.strptime(start_time, '%Y/%m/%d %H:%M')
        end_time = datetime.strptime(end_time, '%Y/%m/%d %H:%M')
        min_player_count = request.form['min_players']
        max_player_count = request.form['max_players']
        validation = 'validation' in request.form

        if (not title or
            not dates or
            not start_time or
            not end_time or
            not min_player_count or
            not max_player_count):
                assert("incorrrect form")
                return redirect(url_for('user.profile'))
        
        new_game = Game(
            title = title,
            about = description,
            min_player_count = min_player_count,
            max_player_count = max_player_count,
            player_count = 1,
            start_time = start_time,
            end_time = end_time,
            validation = validation,
            organizer_id = current_user.id
        )
        db.session.add(new_game)
        db.session.commit()

        new_game.participants.append(current_user)
        db.session.commit()
        return redirect(url_for('user.profile'))
    return render_template('forms/add.html')

@bp.route('/delete/<int:game_id>', methods=['GET', 'POST'])
@login_required
def delete(game_id):
    game = Game.query.get_or_404(game_id)
    if game.organizer_id == current_user.id:
        if request.method == 'POST':
            db.session.query(participants).filter(participants.c.game_id == game.id).delete()
            db.session.query(pending_participants).filter(pending_participants.c.game_id == game.id).delete()

            db.session.delete(game)  # Удаляем игру
            db.session.commit()
            flash('Игра успешно удалена!', 'success')
            return jsonify({'status': 'redirect', 'url': url_for('user.profile')})
    else:
        flash('У вас нет прав на удаление этой игры.', 'danger')
        return jsonify({'status': 'fail'})
    return jsonify({'status': 'fail'})

@bp.route('/join/<int:game_id>', methods=['POST'])
@login_required
def join(game_id):
    game = Game.query.get_or_404(game_id)
    
    # Проверяем, что игра не полная
    if game.player_count < game.max_player_count:
        # Если игра с проверкой
        print(game.validation)
        if game.validation:
            game.pending_participants.append(current_user)
        else:
            game.participants.append(current_user)  # Добавляем пользователя как участника
            game.player_count += 1  # Увеличиваем количество игроков
        
        db.session.commit()
        flash(f"Вы успешно записались на игру {game.title}", "success")
    else:
        flash(f"Игра {game.title} уже набрала максимальное количество игроков", "danger")
        return jsonify({'status': 'fail'})
    
    return jsonify({'status': 'redirect', 'url': url_for('user.profile')})

@bp.route('/leave/<int:game_id>', methods=['GET', 'POST'])
@login_required
def leave(game_id):
    game = Game.query.get_or_404(game_id)
    if current_user in game.participants:
        if request.method == 'POST':
            game.participants.remove(current_user)  # Убираем пользователя из списка участников
            game.player_count -= 1  # Уменьшаем количество игроков

            db.session.commit()
            flash(f"Вы покинули игру {game.title}.", 'info')
            return jsonify({'status': 'redirect', 'url': url_for('user.profile')})
    elif current_user in game.pending_participants:
        if request.method == 'POST':
            game.pending_participants.remove(current_user)  # Убираем пользователя из списка участников

            db.session.commit()
            flash(f"Вы покинули игру {game.title}.", 'info')
            return jsonify({'status': 'redirect', 'url': url_for('user.profile')})
    else:
        flash(f"Вы не участвуете в игре {game.title}.", 'warning')
        return jsonify({'status': 'fail'})
    return jsonify({'status': 'fail'})

@bp.route('/', methods=['GET'])
def home():
    games = Game.query.all()  # Получаем все игры из базы данных
    events = []

    for game in games:
        extended_props = {
            'organizerName': game.organizer.name,
            'description' : game.about,
            'playerCount': game.player_count,
            'registered': current_user.is_authenticated
        }
        if current_user.is_authenticated:
            extended_props.update({
                'userCanJoin': game.player_count < game.max_player_count,
                'joined': current_user in game.participants,
                'isAuthor': game.organizer == current_user
            })

        event = {
            'title': game.title,
            'id': game.id,
            'start': game.start_time.isoformat(),
            'end': game.end_time.isoformat(),
            'extendedProps': extended_props
        }
        events.append(event)

    return render_template('index.html', events=events)

app/routes/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
import os
from .. import db, login_manager
from ..models import User, Game
from ..forms import RegistrationForm, LoginForm

bp = Blueprint('user', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    print(form.submit)
    print(form.validate_on_submit())
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data

        print(username)
        print(email)
        print(password)

        if User.query.filter_by(email=email).first():
            flash('Такая почта уже существует')
            return redirect(url_for('user.register'))

        user = User(
            name=username,
            email=email
            )
        user.set_password(password)

        db.session.add(user)
        db.session.commit()
        login_user(user)

        return redirect(url_for('games.home'))

    return render_template(
        'forms/register.html',
        form=form
        )

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('games.home'))
        else:
            flash('Неверное имя пользователя или пароль')
            return redirect(url_for('user.login'))

    return render_template(
        'forms/login.html',
        form=form
        )

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))

@bp.route('/profile')
@login_required
def profile():
    created_games = current_user.created_games
    participated_games = current_user.joined_games
    pending_games = current_user.pending_games

    participated_games = [game for game in participated_games if game not in created_games]

    return render_template('profile.html',
                           user=current_user,
                           created_games=created_games,
                           participated_games=participated_games,
                           pending_games=pending_games
                           )

@bp.route('/update_profile', methods=['POST'])
@login_required
def update_profile():
    print("YA")
    if request.method == 'POST':
        # Получаем данные из формы
        name = request.form.get('name')
        about = request.form.get('about')

        # Обновляем профиль пользователя
        user = User.query.get(current_user.id)  # Предположим, что используем Flask-Login для текущего пользователя

        if user:
            user.name = name
            user.about = about
            db.session.commit()

            # Возвращаем успешный ответ
            return jsonify({
                'success': True,
                'updated_name': user.name,
                'updated_about': user.about
            })
        else:
            return jsonify({'success': False}), 400

@bp.route('/update_avatar', methods=['POST'])
@login_required
def update_avatar():
    file = request.files.get('avatar')
    if not file:
        return jsonify({'error': 'No file uploaded'}), 400

    filename = secure_filename(f'{current_user.id}_{file.filename}')
    avatar_path = os.path.join('app/static', 'avatars', filename)
    file.save(avatar_path)

    # Обновляем путь в модели пользователя
    current_user.avatar = filename
    db.session.commit()

    return jsonify({'message': 'Avatar updated successfully'})

app/templates/base.html
<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <!--Daterange-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- Bootstrap стили -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <!-- иконки fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- кастомные стили -->
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
</head>
<body>

<!-- навигация -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">The Hatters</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end"
             id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Main</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<!-- контент дочерних шаблонов -->
<div class="mainbody container">
    {% block content %}
    {% endblock %}
</div>

<!-- контент модалок -->
{% block modals %}{% endblock %}

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block modals %}
    {% set include_leave_modal = True %}
    {% set include_delete_modal = True %}
    {% include 'components/modals.html' %}
{% endblock %}

{% block title %}
Gamse hosted
{% endblock %}

{% block content %}

<body>
    <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eventModalLabel">Event Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="card h-100 shadow-sm">
                    <div class="card-header fw-bold" id="modal-event-title">Event Title</div>
                    <div class="card-body">
                        <span class="badge bg-primary" id="modal-organizer-name">Organizer Name</span>
                        <div id="modal-about-section" style="display: none;">
                            <hr>
                            <p class="card-text mt-2"><strong>About:</strong></p>
                            <p class="card-text", id="modal-about-text"></p>
                            <hr>
                        </div>
                        <p class="card-text mt-2" id="modal-players">Players (min - max): <strong id="modal-player-count">0</strong></p>
                        <p class="card-text">Dates:<br>
                        <strong>From:</strong> <span id="modal-start-time">00:00</span><br>
                        <strong>To:</strong> <span id="modal-end-time">00:00</span>
                        </p>
                    </div>
                    </div>
                    </div>
                <div id="modal-join" style="display: none;">
                    <div class="modal-footer d-flex justify-content-between">
                        <button type="button" class="btn btn-primary" id="modal-join-button">Join</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                <div id="modal-register" style="display: none;">
                    <div class="modal-footer d-flex justify-content-between">
                        <span class="text-muted">please register first</span>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                <div id="modal-joined" style="display: none;">
                    <div class="modal-footer d-flex justify-content-between">
                        <span class="text-muted">you are already joined</span>
                        <div>
                            <button type="button" class="btn btn-danger open-leave-modal" data-bs-toggle="modal" data-bs-target="#leaveModal" id="modal-leave-button">Leave</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
                <div id="modal-organizer" style="display: none;">
                    <div class="modal-footer d-flex justify-content-between">
                        <span class="text-muted">you are the organizer</span>
                        <div>
                            <button type="button" class="btn btn-danger open-delete-modal" data-bs-toggle="modal" data-bs-target="#deleteModal" id="modal-delete-button">Delete</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <h1>Games hosted</h1>
        <div id="calendar"></div>
    </div>

    <!-- Подключаем FullCalendar -->
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.17/index.global.min.js'></script>
    <script>
        var EVENTS = JSON.parse('{{ events | tojson }}');
        console.log(EVENTS);
    </script>
    <script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
    <script src="{{ url_for('static', filename='js/modals/join.js') }}"></script>
</body>
</html>

{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block modals %}
    {% set include_leave_modal = True %}
    {% set include_delete_modal = True %}
    {% include 'components/modals.html' %}
{% endblock %}

{% block title %}
Profile
{% endblock %}

{% block content %}
<script src="{{ url_for('static', filename='js/profile.js') }}"></script>

<h1 class="mb-5">Profile</h1>

<!-- Профиль пользователя -->
<div class="container my-5">
    <div class="d-flex align-items-start flex-wrap gap-4">
        <div class="mx-auto mx-md-0" style="width: 150px;">
            <!-- Аватарка -->
            <div class="position-relative d-inline-block">
                <!-- Аватарка -->
                <img src="{{ url_for('static', filename=user.get_avatar()) }}" 
                    alt="Avatar" 
                    id="avatarImage" 
                    class="img-fluid rounded-circle" 
                    style="width: 150px; height: 150px; cursor: pointer; box-shadow: 0 0 5px #00000050;">
                <input type="file" id="avatarInput" name="avatar" class="inputfile" accept="image/*" onchange="previewAvatar(event)">
                <label class="position-absolute top-0 left-0 w-100 h-100 rounded-circle"
                data-bs-toggle="tooltip" title="Edit avatar"
                for="avatarInput"></label>

                <!-- Кнопка редактирования -->
                <a href="javascript:void(0);"
                class="btn btn-sm btn-secondary rounded-circle position-absolute"
                style="top: -10px; right: -10px;"
                data-bs-toggle="tooltip" title="Edit profile"
                id="editProfileBtn">
                    <i class="bi bi-pencil"></i>
                </a>
            </div>
        </div>
        
        <!-- Информация -->
        <form id="profileForm" method="POST">
            <div class="flex-grow-1">
                <div class="mb-3 d-flex align-items-center">
                    <label for="name" class="form-label fw-bold me-2">Name:</label>
                    <p id="nameDisplay" class="mb-0">{{ user.name }}</p>
                    <input type="text" id="nameInput" name="name" value="{{ user.name }}" class="form-control d-none ms-2">
                </div>
                <div class="mb-3 d-flex align-items-center">
                    <label for="email" class="form-label fw-bold me-2">Email:</label>
                    <p id="emailDisplay" class="mb-0">{{ user.email }}</p>
                    <input type="email" id="emailInput" name="email" value="{{ user.email }}" class="form-control d-none ms-2" disabled>
                </div>
                <div class="mb-3">
                    <label for="about" class="form-label fw-bold">About:</label>
                    {% if user.about %}
                        <p id="aboutDisplay" class="mb-0">{{ user.about }}</p>
                    {% else %}
                        <p id="aboutDisplay" class="mb-0 text-muted">You have not written about yourself yet</p>
                    {% endif %}

                    <!-- При редактировании выводим поле для ввода -->
                    <textarea id="aboutInput" name="about" class="form-control d-none ms-2" rows="4">{{ user.about or '' }}</textarea>
                </div>
        
                <!-- Кнопки Save/Cancel -->
                <div id="editButtons" class="d-none mt-3">
                    <button type="button" class="btn btn-secondary" id="cancelEdit">Cancel</button>
                    <button type="submit" class="btn btn-success me-2">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="container my-5">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="join-tab" data-bs-toggle="tab" data-bs-target="#join" type="button" role="tab" aria-controls="join" aria-selected="true">Joined games</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="created-tab" data-bs-toggle="tab" data-bs-target="#created" type="button" role="tab" aria-controls="profile" aria-selected="false">Created games</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="created-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab" aria-controls="profile" aria-selected="false">Pending games</button>
        </li>
    </ul>
  
    <div class="tab-content mt-3" id="myTabContent">
        <div class="tab-pane fade show active" id="join" role="tabpanel" aria-labelledby="join-tab">
            <h4>Participating</h4>
            <div class="mt-4">
                <div class="row">
                    {% for game in participated_games %}
                    <div class="col-md-4 mb-4">
                        <div class="card mb-3 shadow-sm">
                            <div class="card-header fw-bold" id="modal-event-title">{{ game.title }}</div>
                            <div class="card-body">
                                <span class="badge bg-primary" id="modal-organizer-name">{{ game.organizer.name }}</span>
                                {% if game.about %}
                                    <hr>
                                    <p class="card-text mt-2"><strong>About:</strong></p>
                                    <p class="card-text", id="modal-about-text">{{ game.about }}</p>
                                    <hr>
                                {% endif %}
                                <p class="card-text mt-2" id="modal-players">Players ({{ game.min_player_count }} - {{ game.max_player_count }}): <strong id="modal-player-count">{{ game.player_count }}</strong></p>
                                <p class="card-text">Dates:<br>
                                    <strong>From:</strong> <span id="modal-start-time">{{ game.start_time.strftime('%Y/%m/%d %H:%M') }}</span><br>
                                    <strong>To:</strong> <span id="modal-end-time">{{ game.end_time.strftime('%Y/%m/%d %H:%M') }}</span>
                                </p>
                                <div class="row mt-3">
                                    <button type="button"
                                        class="btn btn-danger open-leave-modal"
                                        data-bs-toggle="modal"
                                        data-bs-target="#leaveModal"
                                        id="modal-leave-button"
                                        data-game-id="{{ game.id }}">Leave</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="created" role="tabpanel" aria-labelledby="created-tab">
            <h4>My games</h4>
            <div class="mt-4">
                <div class="row">
                    <div class="col-md-4 mb-4">
                        <div class="card" style="background-color: #24242442; height:300px">
                            <a href="{{ url_for('games.add') }}" class="text-decoration-none text-dark">
                                <div class="card-body d-flex flex-column justify-content-center align-items-center text-center" style="height: 200px;">
                                    <h5 class="mb-3">Create New Game</h5>
                                    <div style="font-size: 64px; line-height: 1;">+</div>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% for game in created_games %}
                    <div class="col-md-4 mb-4">
                        <div class="card mb-3 shadow-sm">
                            <div class="card-header fw-bold" id="modal-event-title">{{ game.title }}</div>
                            <div class="card-body">
                                {% if game.about %}
                                    <p class="card-text mt-2"><strong>About:</strong></p>
                                    <p class="card-text", id="modal-about-text">{{ game.about }}</p>
                                    <hr>
                                {% endif %}
                                <p class="card-text mt-2" id="modal-players">Players ({{ game.min_player_count }} - {{ game.max_player_count }}): <strong id="modal-player-count">{{ game.player_count }}</strong></p>
                                <p class="card-text">Dates:<br>
                                    <strong>From:</strong> <span id="modal-start-time">{{ game.start_time.strftime('%Y/%m/%d %H:%M') }}</span><br>
                                    <strong>To:</strong> <span id="modal-end-time">{{ game.end_time.strftime('%Y/%m/%d %H:%M') }}</span>
                                </p>
                                <div class="row mt-3">
                                    <button type="button"
                                        class="btn btn-danger open-delete-modal"
                                        data-bs-toggle="modal"
                                        data-bs-target="#deleteModal"
                                        id="modal-delete-button"
                                        data-game-id="{{ game.id }}">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="tab-pane fade show" id="pending" role="tabpanel" aria-labelledby="pending-tab">
            <h4>Waiting for approval</h4>
            <div class="mt-4">
                <div class="row">
                    {% for game in pending_games %}
                    <div class="col-md-4 mb-4">
                        <div class="card mb-3 shadow-sm", style="background-color: #fce9e1;">
                            <div class="card-header fw-bold" id="modal-event-title">{{ game.title }}</div>
                                <div class="card-body">
                                    <span class="badge bg-primary" id="modal-organizer-name">{{ game.organizer.name }}</span>
                                    {% if game.about %}
                                        <hr>
                                        <p class="card-text mt-2"><strong>About:</strong></p>
                                        <p class="card-text", id="modal-about-text">{{ game.about }}</p>
                                        <hr>
                                    {% endif %}
                                    <p class="card-text mt-2" id="modal-players">Players ({{ game.min_player_count }} - {{ game.max_player_count }}): <strong id="modal-player-count">{{ game.player_count }}</strong></p>
                                    <p class="card-text">Dates:<br>
                                        <strong>From:</strong> <span id="modal-start-time">{{ game.start_time.strftime('%Y/%m/%d %H:%M') }}</span><br>
                                        <strong>To:</strong> <span id="modal-end-time">{{ game.end_time.strftime('%Y/%m/%d %H:%M') }}</span>
                                    </p>
                                    <div class="row mt-3">
                                        <button type="button"
                                            class="btn btn-danger open-leave-modal"
                                            data-bs-toggle="modal"
                                            data-bs-target="#leaveModal"
                                            id="modal-leave-button"
                                            data-game-id="{{ game.id }}">Leave</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}